spring:
  config:
    activate:
      on-profile: supabase

  datasource:
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.bnmrpsluwwlxxrbhgxwa
    password: VNsJaFsT3E6Jhnan
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    url: jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
    user: postgres.bnmrpsluwwlxxrbhgxwa
    password: VNsJaFsT3E6Jhnan
    baseline-on-migrate: true
    locations: classpath:db/migration
